### ISSUE TITLE
Use Operator Framework for Instascale controller

### ISSUE THREAD

**Issue by asm582** [project-codeflare/instascale#64]
@KPostOffice  should we close this issue in a different repo: https://github.com/openshift/machine-api-operator/issues/1138

**Comment by KPostOffice** [comment]
Ahh, yes. My bad

**Comment by anishasthana** [comment]
Is this effectively a dupe of https://github.com/project-codeflare/instascale/issues/47 and https://github.com/project-codeflare/instascale/issues/48?

**Comment by anishasthana** [comment]
This is a duplicate of #47 and #48
