### ISSUE TITLE
Create e2e tests for InstaScale

### ISSUE THREAD

**Issue by anishasthana** [project-codeflare/instascale#66]
Create basic tests that can be run against an OpenShift cluster to verify InstaScale functionality.

We should make sure to verify both MachineSet and MachinePool functionality.

For now, these tests would assume that you already have an OpenShift cluster spun up and configured correctly for InstaScale functionality. A follow-on to this will be running the tests in CI.

**Comment by anishasthana** [comment]
fyi @sutaakar

**Comment by Fiona-Waters** [comment]
[WIP PR](https://github.com/project-codeflare/codeflare-operator/pull/311) for hypershift e2e. To follow on from - https://github.com/project-codeflare/instascale/pull/129
