### ISSUE TITLE
Create instascale design document

### ISSUE THREAD

**Issue by dimakis** [project-codeflare/instascale#92]

**Comment by KPostOffice** [comment]
@dimakis I see that this is ready for review. Is there a Google Doc or ADR that I can take a look at?

**Comment by dimakis** [comment]
> @dimakis I see that this is ready for review. Is there a Google Doc or ADR that I can take a look at?

Just that Google doc that we have already been commenting on. I've to get back to it. 

By all means, add suggestions etc.

**Comment by KPostOffice** [comment]
https://docs.google.com/document/d/15t9ha7K8rH0ACPZyBD_F-2CKqBabSBbN1cmzDVkV9Gs/edit#heading=h.swxey7fqzz6d
