### ISSUE TITLE
Instascale panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by kpouget** [project-codeflare/instascale#95]
When running the MCAD scale test in the CI, we observe [the following panic](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/813/pull-ci-openshift-psap-ci-artifacts-main-codeflare-light/1674345516713906176/artifacts/light/gather-extra/artifacts/pods/opendatahub_instascale-instascale-745c5996d4-bqshb_instascale_previous.log) of `instascale`:
```
I0629 09:35:38.640517       1 appwrapper_controller.go:225] Found Appwrapper named aw004-300s that has status Pending
I0629 09:35:38.640534       1 appwrapper_controller.go:283] The instanceRequired array: []
E0629 09:35:38.640595       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 401 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1a7dfe0?, 0xc0001cc438})
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:74 +0x86
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0001ac0c0?})
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1a7dfe0, 0xc0001cc438})
	/usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/project-codeflare/instascale/controllers.discoverInstanceTypes(0xc000a38000)
	/workspace/controllers/appwrapper_controller.go:286 +0x370
github.com/project-codeflare/instascale/controllers.onAdd({0x1b57f40?, 0xc000a38000?})
	/workspace/controllers/appwrapper_controller.go:228 +0x10e
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/opt/app-root/src/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnAdd({0x1ca2a28?, {0x1e4ce70?, 0xc000438510?}}, {0x1b57f40, 0xc000a38000})
	/opt/app-root/src/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/controller.go:264 +0x64
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/opt/app-root/src/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/shared_informer.go:787 +0xaf
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00058af38?, {0x1e38020, 0xc000494b10}, 0x1, 0xc00018ed80)
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0001b2000?, 0x3b9aca00, 0x0, 0xf1?, 0xc00058af88?)
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000206800?)
	/opt/app-root/src/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/opt/app-root/src/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:71 +0x85
panic: runtime error: index out of range [0] with length 0 [recovered]
```

`instascale` is [running](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/813/pull-ci-openshift-psap-ci-artifacts-main-codeflare-light/1674345516713906176/artifacts/light/gather-extra/artifacts/deployments.json)  from `quay.io/project-codeflare/instascale-controller:v0.0.4`, deployed by these two ODH Kfdef:
```
  - https://raw.githubusercontent.com/opendatahub-io/odh-manifests/master/kfdef/odh-core.yaml
  - https://raw.githubusercontent.com/opendatahub-io/distributed-workloads/main/codeflare-stack-kfdef.yaml
```

The issue might be linked with [this MCAD ticket](https://github.com/project-codeflare/multi-cluster-app-dispatcher/issues/436).

The Appwrapper mentioned in the log is certainly [this one](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/813/pull-ci-openshift-psap-ci-artifacts-main-codeflare-light/1674345516713906176/artifacts/light/test/artifacts/000_test-case_gpu_unschedulable/001__mcad_load_test/000__codeflare__generate_mcad_load/generator-artifacts/aw004-300s.yaml). Its status is visible in [this file](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/813/pull-ci-openshift-psap-ci-artifacts-main-codeflare-light/1674345516713906176/artifacts/light/test/artifacts/000_test-case_gpu_unschedulable/001__mcad_load_test/000__codeflare__generate_mcad_load/appwrappers.yaml). The resource is expected _not_ to run, because no GPU is made available for it.

**Comment by VanillaSpoon** [comment]
Thanks @kpouget 
I feel this may be related to #96

**Comment by kpouget** [comment]
good catch @VanillaSpoon, I agree that it's related:
```
I0629 09:35:38.640534       1 appwrapper_controller.go:283] The instanceRequired array: []
```
so of course
```
instanceName := instanceRequired[idx+id]
```
this will crash :) 

Now I see this above:
```
	for k, v := range aw.Labels {
		if k == "orderedinstance" {
			instanceRequired = strings.Split(v, "_")
		}
	}
```
and I'm wondering where this is documented, to better understand this `orderedinstance` label 🤔

**Comment by VanillaSpoon** [comment]
In terms of documentation we are quite limited, but have plans to further add machinepool, and machineset documentation that will hopefully provide further information on orderedInstances soon. 

I will also bring @dimakis  to this discussion as he may have more information.

**Comment by asm582** [comment]
@VanillaSpoon  do we know if this issue is resolved with one of your merged PRs?

**Comment by VanillaSpoon** [comment]
Hey @asm582,
Yes, this has been resolved. I have left the conversion open in regards to providing documentation on Machinepools/machinesets. 

However, there is another ticket open for documenting these. This issue can be closed.
